version: '3'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authPostgres
    volumes:
      - './services/postgres/data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      default:

  rabbit:
    image: bitnami/rabbitmq
    ports:
      - "1500:15672"
    networks:
      default:

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - './auth-service/node_modules:/app/node_modules'
      - './auth-service/src:/app/src'
    env_file:
      - auth-service/.env
    command:
      - npm
      - run
      - start:dev
    depends_on:
      - postgres
      - rabbit
    networks:
      default:

  todo-list:
    build:
      context: ./todo-list
      dockerfile: Dockerfile
    volumes:
      - './todo-list/node_modules:/app/node_modules'
      - './todo-list/src:/app/src'
    env_file:
      - todo-list/.env
    command:
      - npm
      - run
      - start:dev
    depends_on:
      - rabbit
      - postgres
    networks:
      default:

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - todo-list
    networks:
      default:

volumes:
  pg:
networks:
  default:




